CREATE DATABASE finesse_db;

USE finesse_db;

CREATE TABLE users (
    user_name VARCHAR(255) NOT NULL,
    password VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL,
    id INTEGER(30) NOT NULL,
    PRIMARY KEY (id)
);

CREATE TABLE goals (
    id int NOT NULL AUTO_INCREMENT,
    goal_name VARCHAR(255) NOT NULL,
    removed BOOLEAN NOT NULL,
    createDate DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id) 
);
